MODEL:
  TYPE: unet
  NAME: pretrain
  DROP_PATH_RATE: 0.0
  RECOVER_TARGET_TYPE: masked

DATA:
  IMG_SIZE: 256
  FILTER_TYPE: mfm
  SAMPLE_RATIO: 0.5
  MASK_RADIUS1: 16
  MASK_RADIUS2: 999
  DATASET: 'crack'

TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  BASE_LR: 3e-4
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-6
  WEIGHT_DECAY: 0.05
  CLIP_GRAD: 3.0
  OPTIMIZER:
    BETAS: (0.9, 0.95)
    
PRINT_FREQ: 100
SAVE_FREQ: 10
TAG: mfm_pretrain__unet__img512__300ep/debug
